export const ADD_INGREDIENT = "ADD_INGREDIENT";

export const FETCH_INGREDIENTS = "FETCH_INGREDIENTS";

export const FETCH_CATEGORIES = "FETCH_CATEGORIES";

export const ADD_CATEGORY = "ADD_CATEGORY";
